In [22]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.rand(17,3), columns=['a', 'b', 'c'])
df

           a         b         c
0   0.016028  0.236667  0.476063
1   0.455650  0.206363  0.901758
2   0.348236  0.948110  0.495833
3   0.842356  0.967799  0.428226
4   0.561852  0.490362  0.904019
5   0.493171  0.109742  0.471608
6   0.225435  0.523481  0.622689
7   0.929322  0.522086  0.203688
8   0.413658  0.117339  0.817443
9   0.153744  0.721036  0.151157
10  0.873260  0.240099  0.021506
11  0.302579  0.127396  0.938434
12  0.672737  0.697773  0.875801
13  0.886831  0.658602  0.381642
14  0.000400  0.488354  0.786319
15  0.070703  0.743450  0.011060
16  0.767423  0.264673  0.423299

In [30]:
from typing import Iterator
class PredFunc:
    @staticmethod
    def df_chunker(df: pd.DataFrame, step_size: int) -> Iterator[tuple[pd.DataFrame, int]]:
        return ((df[pos:pos+step_size], pos) for pos in range(0, df.shape[0], step_size))

step = 4
for idx, (df_batch, pos) in enumerate(PredFunc.df_chunker(df, step)):
    print(f'Batch {idx}: {pos}/{df.shape[0]-1}')
    print(df_batch)

Batch 0: 0/16
          a         b         c
0  0.016028  0.236667  0.476063
1  0.455650  0.206363  0.901758
2  0.348236  0.948110  0.495833
3  0.842356  0.967799  0.428226
Batch 1: 4/16
          a         b         c
4  0.561852  0.490362  0.904019
5  0.493171  0.109742  0.471608
6  0.225435  0.523481  0.622689
7  0.929322  0.522086  0.203688
Batch 2: 8/16
           a         b         c
8   0.413658  0.117339  0.817443
9   0.153744  0.721036  0.151157
10  0.873260  0.240099  0.021506
11  0.302579  0.127396  0.938434
Batch 3: 12/16
           a         b         c
12  0.672737  0.697773  0.875801
13  0.886831  0.658602  0.381642
14  0.000400  0.488354  0.786319
15  0.070703  0.743450  0.011060
Batch 4: 16/16
           a         b         c
16  0.767423  0.264673  0.423299